<?php

namespace Armd\ResourceBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class HallController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Armd\ResourceBundle\Controller\HallController();
        return $instance;
    }
}
