admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

sonata_user_impersonating:
    pattern:   /admin
    defaults:  { _controller: SonataUserBundle:AdminSecurity:login }

sonata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /media/gallery

media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media

sip_multiple_upload:
    resource: "@SIPMultipleUploadBundle/Resources/config/routing.yml"
    prefix:   /

SIPResourceBundle:
    resource: '@SIPResourceBundle/Resources/routing/routing.yml'
    prefix:   /
