parameters:
    sip.resourse.setting.admin.class: SIP\ResourceBundle\Admin\SettingAdmin
    sip.resourse.setting.model.class: SIP\ResourceBundle\Entity\Setting

    sip.resourse.meta.admin.class: SIP\ResourceBundle\Admin\MetaDataAdmin
    sip.resourse.meta.model.class: SIP\ResourceBundle\Entity\MetaData

services:
    sip.resourse.setting.admin:
        class: %sip.resourse.setting.admin.class%
        tags:
            - { name: sonata.admin, manager_type: orm, group: content, label: Setting }
        arguments: [null, %sip.resourse.setting.model.class%, null, @service_container]

    sip.resourse.meta.admin:
        class: SIP\ResourceBundle\Admin\MetaDataAdmin
        arguments: [null, SIP\ResourceBundle\Entity\MetaData, null]
        tags:
            - { name: sonata.admin, manager_type: orm, group: dict, label: MetaData }

    sonata.media.admin.gallery:
        class: %sonata.media.admin.gallery.class%
        tags:
            - { name: sonata.admin, manager_type: orm, group: sonata_media, label: gallery, show_in_dashboard: false }
        arguments: [null, %sonata.media.admin.gallery.entity%, %sonata.media.admin.gallery.controller%, @sonata.media.pool]
        calls:
            - [setTranslationDomain, [ %sonata.media.admin.gallery.translation_domain% ] ]
            - [setTemplates, [ {list: SonataMediaBundle:GalleryAdmin:list.html.twig} ] ]