<?php

namespace Proxies\__CG__\Armd\ResourceBundle\Entity\Guide;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class GuideItem extends \Armd\ResourceBundle\Entity\Guide\GuideItem implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', 'exhibit', 'hall', 'titleExhibit', 'descriptionExhibit', 'photoExhibit', 'iconExhibit', 'metadataExhibit', 'audio', 'position', 'moves', 'guide');
        }

        return array('__isInitialized__', 'id', 'exhibit', 'hall', 'titleExhibit', 'descriptionExhibit', 'photoExhibit', 'iconExhibit', 'metadataExhibit', 'audio', 'position', 'moves', 'guide');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (GuideItem $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitleExhibit($titleExhibit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitleExhibit', array($titleExhibit));

        return parent::setTitleExhibit($titleExhibit);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitleExhibit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitleExhibit', array());

        return parent::getTitleExhibit();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescriptionExhibit($descriptionExhibit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescriptionExhibit', array($descriptionExhibit));

        return parent::setDescriptionExhibit($descriptionExhibit);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescriptionExhibit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescriptionExhibit', array());

        return parent::getDescriptionExhibit();
    }

    /**
     * {@inheritDoc}
     */
    public function setMetadataExhibit($metadataExhibit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMetadataExhibit', array($metadataExhibit));

        return parent::setMetadataExhibit($metadataExhibit);
    }

    /**
     * {@inheritDoc}
     */
    public function getMetadataExhibit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMetadataExhibit', array());

        return parent::getMetadataExhibit();
    }

    /**
     * {@inheritDoc}
     */
    public function setPosition($position)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPosition', array($position));

        return parent::setPosition($position);
    }

    /**
     * {@inheritDoc}
     */
    public function getPosition()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPosition', array());

        return parent::getPosition();
    }

    /**
     * {@inheritDoc}
     */
    public function setMoves($moves)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMoves', array($moves));

        return parent::setMoves($moves);
    }

    /**
     * {@inheritDoc}
     */
    public function getMoves()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMoves', array());

        return parent::getMoves();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhotoExhibit(\Armd\ResourceBundle\Entity\Media\Media $photoExhibit = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhotoExhibit', array($photoExhibit));

        return parent::setPhotoExhibit($photoExhibit);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhotoExhibit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhotoExhibit', array());

        return parent::getPhotoExhibit();
    }

    /**
     * {@inheritDoc}
     */
    public function setIconExhibit(\Armd\ResourceBundle\Entity\Media\Media $iconExhibit = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIconExhibit', array($iconExhibit));

        return parent::setIconExhibit($iconExhibit);
    }

    /**
     * {@inheritDoc}
     */
    public function getIconExhibit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIconExhibit', array());

        return parent::getIconExhibit();
    }

    /**
     * {@inheritDoc}
     */
    public function setAudio(\Armd\ResourceBundle\Entity\Media\Media $audio = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAudio', array($audio));

        return parent::setAudio($audio);
    }

    /**
     * {@inheritDoc}
     */
    public function getAudio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAudio', array());

        return parent::getAudio();
    }

    /**
     * {@inheritDoc}
     */
    public function setExhibit(\Armd\ResourceBundle\Entity\Exhibit $exhibit = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExhibit', array($exhibit));

        return parent::setExhibit($exhibit);
    }

    /**
     * {@inheritDoc}
     */
    public function getExhibit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExhibit', array());

        return parent::getExhibit();
    }

    /**
     * {@inheritDoc}
     */
    public function setHall(\Armd\ResourceBundle\Entity\Hall $hall = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHall', array($hall));

        return parent::setHall($hall);
    }

    /**
     * {@inheritDoc}
     */
    public function getHall()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHall', array());

        return parent::getHall();
    }

    /**
     * {@inheritDoc}
     */
    public function setGuide(\Armd\ResourceBundle\Entity\Guide\Guide $guide = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGuide', array($guide));

        return parent::setGuide($guide);
    }

    /**
     * {@inheritDoc}
     */
    public function getGuide()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGuide', array());

        return parent::getGuide();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getVirtualExhibit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVirtualExhibit', array());

        return parent::getVirtualExhibit();
    }

    /**
     * {@inheritDoc}
     */
    public function getVirtualAudio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVirtualAudio', array());

        return parent::getVirtualAudio();
    }

    /**
     * {@inheritDoc}
     */
    public function getVirtualPhoto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVirtualPhoto', array());

        return parent::getVirtualPhoto();
    }

    /**
     * {@inheritDoc}
     */
    public function getVirtualIcon()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVirtualIcon', array());

        return parent::getVirtualIcon();
    }

}
